language: go
go: "1.13.x"

cache:
  directories:
  - $GOPATH/pkg

env:
  global:
  - GO111MODULE=on
  - GOARCH=amd64
  matrix:
  - GOOS=linux
  - GOOS=darwin
  - GOOS=windows

script: 
- go test -v -failfast ./...
- gofmt -w -s $(go list -f '{{ .Dir }}' ./...)
- git diff --exit-code
